volumes:
  rglua_database_internals:
    labels: 
      clear: "rglua"
      
services:
  rglua_db:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - rglua_database_internals:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 1s
      retries: 10
      start_period: 20s

  # TODO: WIP enable/disable depending on env var for dev/prod
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8888:8080

  blue_player:
    build:
      context: ../
      dockerfile: ./player/deployment/Dockerfile
      args:
        - PORT=1111
    expose:
      - "1111"
    command: " -p 1111"
  red_player:
    build:
      context: ../
      dockerfile: ./player/deployment/Dockerfile
      args:
        - PORT=2222
    expose:
      - "2222"
    command: " -p 2222"

  referee:
    build:
      context: ../
      dockerfile: ./referee/deployment/Dockerfile
    expose:
      - "3333"
    depends_on:
      blue_player:
        condition: service_started
      red_player:
        condition: service_started
      rglua_db:
        condition: service_healthy

  matchmaker:
    build:
      context: ../
      dockerfile: ./matchmaker/deployment/Dockerfile
    expose:
      - "4444"
    depends_on:
      referee:
        condition: service_started
      rglua_db:
        condition: service_healthy

  bouncer:
    build:
      context: ../
      dockerfile: ./bouncer/deployment/Dockerfile
    ports:
      - 5555:5555
    depends_on:
      matchmaker:
        condition: service_started
      rglua_db:
        condition: service_healthy

